package modelo;
// Generated 25/10/2017 08:09:13 by Hibernate Tools 4.3.1



/**
 * Cidade generated by hbm2java
 */
public class Cidade implements java.io.Serializable {

     private int idcidade;
     private Integer cidadeIbge;
     private String idunidFed;
     private String nomedesc;

    public Cidade() {
    }

	
    public Cidade(int idcidade) {
        this.idcidade = idcidade;
    }
    public Cidade(int idcidade, Integer cidadeIbge, String idunidFed, String nomedesc) {
       this.idcidade = idcidade;
       this.cidadeIbge = cidadeIbge;
       this.idunidFed = idunidFed;
       this.nomedesc = nomedesc;
    }
   
    public int getIdcidade() {
        return this.idcidade;
    }
    
    public void setIdcidade(int idcidade) {
        this.idcidade = idcidade;
    }
    public Integer getCidadeIbge() {
        return this.cidadeIbge;
    }
    
    public void setCidadeIbge(Integer cidadeIbge) {
        this.cidadeIbge = cidadeIbge;
    }
    public String getIdunidFed() {
        return this.idunidFed;
    }
    
    public void setIdunidFed(String idunidFed) {
        this.idunidFed = idunidFed;
    }
    public String getNomedesc() {
        return this.nomedesc;
    }
    
    public void setNomedesc(String nomedesc) {
        this.nomedesc = nomedesc;
    }




}


