package modelo;
// Generated 25/10/2017 08:09:13 by Hibernate Tools 4.3.1



/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private String idunidFed;
     private String nomeestado;

    public Estado() {
    }

	
    public Estado(String idunidFed) {
        this.idunidFed = idunidFed;
    }
    public Estado(String idunidFed, String nomeEstado) {
       this.idunidFed = idunidFed;
       this.nomeestado = nomeEstado;
    }
   
    public String getIdunidFed() {
        return this.idunidFed;
    }
    
    public void setIdunidFed(String idunidFed) {
        this.idunidFed = idunidFed;
    }
    public String getnomeestado() {
        return this.nomeestado;
    }
    
    public void setnomeestado(String nomeestado) {
        this.nomeestado = nomeestado;
    }




}


