package modelo;
// Generated 25/10/2017 08:09:13 by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * Inscritoscurso generated by hbm2java
 */
public class Inscritoscurso  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_inscritocurso_id")
    private int id;
    private Integer idaluno;
    private Integer idcurso;

    public Inscritoscurso() {
    }
	
    public Inscritoscurso(int id) {
        this.id = id;
    }
    public Inscritoscurso(int id, Integer idaluno, Integer idcurso) {
       this.id = id;
       this.idaluno = idaluno;
       this.idcurso = idcurso;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdaluno() {
        return this.idaluno;
    }
    
    public void setIdaluno(Integer idaluno) {
        this.idaluno = idaluno;
    }
    public Integer getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(Integer idcurso) {
        this.idcurso = idcurso;
    }
}


